version: '3.8'
services:
  blackboard-bot:
    build: .
    container_name: wow-blackboard-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./blackboard.db:/app/blackboard.db
